#############################################################################
# Makefile for building: Ps
# Generated by qmake (2.01a) (Qt 4.8.3) on: Mon Jan 7 11:33:36 2013
# Project:  Ps.pro
# Template: app
# Command: /home/yuri/下载/qt-everywhere-commercial-src-4.8.3/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.3/mkspecs/linux-g++ -o Makefile Ps.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.3/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.3/include/QtCore -I/usr/local/Trolltech/Qt-4.8.3/include/QtGui -I/usr/local/Trolltech/Qt-4.8.3/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.3/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.3/lib -lpython2.6 -lcurl -lQtGui -L/usr/local/Trolltech/Qt-4.8.3/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/yuri/下载/qt-everywhere-commercial-src-4.8.3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/browser/main.cpp \
		src/browser/browser.cpp \
		src/browser/MM.cpp \
		src/browser/filemenu.cpp \
		src/browser/menubar.cpp \
		src/lib/mm.c \
		src/util/log.c \
		src/lib/web.c moc_browser.cpp \
		moc_filemenu.cpp \
		moc_menubar.cpp
OBJECTS       = main.o \
		browser.o \
		MM.o \
		filemenu.o \
		menubar.o \
		mm.o \
		log.o \
		web.o \
		moc_browser.o \
		moc_filemenu.o \
		moc_menubar.o
DIST          = /usr/local/Trolltech/Qt-4.8.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/include_source_dir.prf \
		Ps.pro
QMAKE_TARGET  = Ps
DESTDIR       = 
TARGET        = Ps

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Ps.pro  /usr/local/Trolltech/Qt-4.8.3/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.3/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.3/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.3/mkspecs/linux-g++ -o Makefile Ps.pro
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.3/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.3/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.3/mkspecs/linux-g++ -o Makefile Ps.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Ps1.0.0 || $(MKDIR) .tmp/Ps1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Ps1.0.0/ && $(COPY_FILE) --parents src/browser/browser.h src/browser/MM.h src/browser/filemenu.h src/browser/menubar.h src/include/config.h src/include/init_clear.h src/include/log.h src/include/mm.h src/include/web.h .tmp/Ps1.0.0/ && $(COPY_FILE) --parents src/browser/main.cpp src/browser/browser.cpp src/browser/MM.cpp src/browser/filemenu.cpp src/browser/menubar.cpp src/lib/mm.c src/util/log.c src/lib/web.c .tmp/Ps1.0.0/ && (cd `dirname .tmp/Ps1.0.0` && $(TAR) Ps1.0.0.tar Ps1.0.0 && $(COMPRESS) Ps1.0.0.tar) && $(MOVE) `dirname .tmp/Ps1.0.0`/Ps1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Ps1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_browser.cpp moc_filemenu.cpp moc_menubar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_browser.cpp moc_filemenu.cpp moc_menubar.cpp
moc_browser.cpp: src/browser/menubar.h \
		src/browser/filemenu.h \
		src/browser/MM.h \
		src/include/mm.h \
		src/include/size.h \
		src/include/log.h \
		src/include/config.h \
		src/browser/browser.h
	/usr/local/Trolltech/Qt-4.8.3/bin/moc $(DEFINES) $(INCPATH) src/browser/browser.h -o moc_browser.cpp

moc_filemenu.cpp: src/browser/MM.h \
		src/include/mm.h \
		src/include/size.h \
		src/include/log.h \
		src/include/config.h \
		src/browser/filemenu.h
	/usr/local/Trolltech/Qt-4.8.3/bin/moc $(DEFINES) $(INCPATH) src/browser/filemenu.h -o moc_filemenu.cpp

moc_menubar.cpp: src/browser/filemenu.h \
		src/browser/MM.h \
		src/include/mm.h \
		src/include/size.h \
		src/include/log.h \
		src/include/config.h \
		src/browser/menubar.h
	/usr/local/Trolltech/Qt-4.8.3/bin/moc $(DEFINES) $(INCPATH) src/browser/menubar.h -o moc_menubar.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/browser/main.cpp src/include/init_clear.h \
		src/include/log.h \
		src/include/size.h \
		src/include/mm.h \
		src/include/web.h \
		src/include/config.h \
		src/browser/browser.h \
		src/browser/menubar.h \
		src/browser/filemenu.h \
		src/browser/MM.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/browser/main.cpp

browser.o: src/browser/browser.cpp src/browser/browser.h \
		src/browser/menubar.h \
		src/browser/filemenu.h \
		src/browser/MM.h \
		src/include/mm.h \
		src/include/size.h \
		src/include/log.h \
		src/include/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o browser.o src/browser/browser.cpp

MM.o: src/browser/MM.cpp src/browser/MM.h \
		src/include/mm.h \
		src/include/size.h \
		src/include/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MM.o src/browser/MM.cpp

filemenu.o: src/browser/filemenu.cpp src/browser/filemenu.h \
		src/browser/MM.h \
		src/include/mm.h \
		src/include/size.h \
		src/include/log.h \
		src/include/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filemenu.o src/browser/filemenu.cpp

menubar.o: src/browser/menubar.cpp src/browser/menubar.h \
		src/browser/filemenu.h \
		src/browser/MM.h \
		src/include/mm.h \
		src/include/size.h \
		src/include/log.h \
		src/include/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menubar.o src/browser/menubar.cpp

mm.o: src/lib/mm.c src/include/log.h \
		src/include/size.h \
		src/include/mm.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mm.o src/lib/mm.c

log.o: src/util/log.c src/include/log.h \
		src/include/size.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o log.o src/util/log.c

web.o: src/lib/web.c src/include/web.h \
		src/include/config.h \
		src/include/log.h \
		src/include/size.h \
		src/include/init_clear.h \
		src/include/mm.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o web.o src/lib/web.c

moc_browser.o: moc_browser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_browser.o moc_browser.cpp

moc_filemenu.o: moc_filemenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filemenu.o moc_filemenu.cpp

moc_menubar.o: moc_menubar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menubar.o moc_menubar.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

